appium/python-client

appium/webdriver/webdriver.py
test/functional/android/appium_tests.py

The Android api demo app had changed its package name.
Also, there are more arguments that can be sent to the `driver.start_activity` method. Fixes #65.

Fix start_activity

---

appium/__init__.py

Catch `ImportError` if the user does not have the [SauceClient](https://pypi.python.org/pypi/sauceclient/0.1.0) installed. Resolves #69.

Fix handling of sauce test case so ImportError is suppressed

---

appium/webdriver/webdriver.py

`tap` method was sending `release`, thereby bypassing the special logic for single taps on the server.
Fixes appium/appium#4111

Fix issue with single tap

---

appium/webdriver/webdriver.py

dict.has_key() was removed in Python 3, changed to in.

Fix start_activity for Python 3.x

---

appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
appium/webdriver/webelement.py
test/functional/android/appium_tests.py

`WebElement` needs a `location_in_view` method to replace `location`, which is deprecated. Resolves #86.
Also fix a couple of bugs.

Add location_in_view property

---

appium/webdriver/webdriver.py

Duration sent into `driver.tap` ought to be `ms`, like the documentation says, not `s`, as the multi-tap case handles it.
Fixes #89

Make tap duration be handled as ms, not s

---

appium/webdriver/webdriver.py

add an wait_activity method for WebDriver which is helpful to make test case stable without sacrificing efficiency (sleeping a long time does).

add wait_activity method for WebDriver

---

appium/webdriver/webdriver.py
test/functional/android/appium_tests.py

The Appium server supports sending in the name of the file to query for strings. Add the parameter to the client method.
Resolves #93.

Add string file argument to driver.app_strings

---

appium/webdriver/connectiontype.py
appium/webdriver/webdriver.py
setup.py
test/functional/android/network_connection_tests.py

[enum34](https://pypi.python.org/pypi/enum34) does not, and will not, support Python 3.5, so the client can't be installed. Remove the dependency and just use a set of predefined constants on a class.
Resolves #102

Remove dependency on enum

---

appium/saucetestcase.py

The module 'new' was removed. Instead of new.newclass, use type().
This fixed issue #112.

Fix saucetestcase to run under Python3.

---

appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/functional/ios/appium_tests.py
test/functional/ios/desired_capabilities.py

Added the call to /appium/simulator/touch_id and accompanying tests

Added touchId to driver

---

appium/webdriver/common/mobileby.py
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
appium/webdriver/webelement.py
test/functional/ios/appium_tests.py
test/functional/ios/find_by_ios_predicate_tests.py

First time pull request, go easy on me =(

Adding clear and find elements by ios predicate string.

---

appium/webdriver/webdriver.py

Found this change in 1.4
https://github.com/appium/appium/blob/master/CHANGELOG.md#changes-in-version-14-from-137
```
new capability disableAndroidWatchers
deprecated capability stopAppOnReset
```

dontStopAppOnReset instead of stopAppOnReset

---

appium/webdriver/common/mobileby.py
appium/webdriver/webdriver.py
appium/webdriver/webelement.py

from: Request: Please add support for -ios class chain #171
https://github.com/appium/python-client/issues/171#issuecomment-307268104

add class chain

---

appium/webdriver/webdriver.py
appium/webdriver/webelement.py
test/functional/ios/desired_capabilities.py
test/functional/ios/find_by_ios_class_chain_tests.py

Update for add class chain #172
- add tests for `find_element_by_ios_class_chain`/`find_elements_by_ios_class_chain`
- rename the method name, `find_elements_by_class_chain`, to `find_elements_by_ios_class_chain `

add tests for ios class chain and rename find_elements_by_class_chain  method

---

README.md

close: Request: Please add support for -ios class chain #171

append class chain related descriptions in README

---

.gitignore
README.md
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/functional/android/appium_tests.py

https://github.com/appium/appium/issues/8674

Add method for getting current package

---

appium/webdriver/webdriver.py

Only if key_name, key, and strategy are None do we need to set the strategy to 'tapOutside'. This change allows setting just the strategy to some other value, like 'swipeDown'.

Allow different strategies for hide_keyboard

---

.gitignore
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/functional/android/appium_tests.py
test/functional/ios/appium_tests.py

Actually, finished https://github.com/appium/python-client/pull/84

Add endpoints for lock/unlock

---

appium/webdriver/webdriver.py
test/functional/ios/appium_tests.py
test/functional/ios/find_by_ios_class_chain_tests.py

- Add `appium:` prefix for capabilities except for items defined by W3C
- Add `forceMjsonwp` capability to force request format MJSONWP format.
- By default, the client send `{'firstMatch': [{}], 'alwaysMatch': always_match}` style
- We can remove this process after finishing migrating from MJSONWP to W3C completely.
- Change some logic from WebDriver's w3c spec
- `find_element/s` related methos since in W3C, `id` is convert to `css selector` style
- https://github.com/appium/python-client/pull/196/files#diff-30b129e415d9d5342e47b17ebdea5536R194
- Change some test cases to work the latest appium server(1.7.2)
----
- Run with W3C
```
[debug] [MJSONWP] Responding to client with driver.getSize() result: {"width":93,"height":33}
[HTTP] <-- GET …
```

add appium prefix in create session and fix find_elements for W3C

---

appium/webdriver/webdriver.py

This endpoint accepts argument and it is more convenient to pass these via POST request (actually, Java client does not accept anything else %) ). GET endpoint will still be there: https://github.com/appium/appium-base-driver/pull/185

Change QUERY_APP_STATE request type to POST

---

appium/webdriver/webdriver.py

To lock forever until `unlock()` is called:
device.lock()
To lock for 5 seconds:
device.lock(5)

Set None as default value to lock device

---

appium/webdriver/webdriver.py

Fix: function `find_element_by_image` always raise an exception: "TypeError: Object of type 'bytes' is not JSON serializable" #228 
`encodestring` generate byte data in Python 3. Thus, we should encode it to string.
```
>>> import base64
>>> base64.encodestring(b'hello')
'aGVsbG8=\n'
```
```
>>> import base64
>>> base64.encodestring(b'hello')
b'aGVsbG8=\n'
```
`b64_data` should be base64 encoded string.
This way is as same as https://github.com/SeleniumHQ/selenium/blob/6b5fe890da7d1592693d1dfcf795d882fc0426c5/py/selenium/webdriver/firefox/firefox_profile.py#L180 way.

fix base64 encoded string

---

README.md
appium/webdriver/common/mobileby.py
appium/webdriver/webdriver.py

add `-android viewtag` for Espresso Driver #237

add tag view for android

---

.pylintrc
.travis.yml
appium/saucetestcase.py
appium/webdriver/common/multi_action.py
appium/webdriver/common/touch_action.py
appium/webdriver/errorhandler.py
appium/webdriver/imagelement.py
appium/webdriver/webdriver.py
appium/webdriver/webelement.py
ci-requirements.txt
test/unit/multi_action_tests.py

This PR is proposal.
📝 I'll ask recommended preferences in python channel
----
Current this repository has no travis preference. No pylint, but this repository has a few unit tests as well. https://pylint.readthedocs.io/en/latest/technical_reference/features.html provide some compatibility checking for Python 2 and 3.
So, what about adding travis and `pylint`?
---
- Add travis.yml
- Add template of `.pylintrc`
- `missing-docstring`
- `empty-docstring`
- `too-few-public-methods`
- `invalid-name`
- `duplicate-code`
- No
- All unit tests are passed

Add travis to run pylint and unit tests

---

.travis.yml
appium/webdriver/webdriver.py
ci-requirements.txt
test/__init__.py
test/unit/multi_action_tests.py
test/unit/touch_action_tests.py

add selenium into ci-requirements, fix pylint, add --py3k

---

appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py

the toggle wifi command is added according to https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L489.

add toggle wifi command

---

README.md

Updates `finiding` to `finding`

[fix] Readme typo 

---

appium/webdriver/webdriver.py

related: https://github.com/appium/ruby_lib_core/pull/138
```
[HTTP]
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{"appium:newCommandTimeout":240,"appium:app":"/Users/kazuaki/GitHub/python-client/test/apps/ApiDemos-debug.apk","appium:deviceName":"Android Emulator","platformName":"Android"}]},"desiredCapabilities":{"deviceName":"Android Emulator","app":"/Users/kazuaki/GitHub/python-client/test/apps/ApiDemos-debug.apk","platformName":"Android","newCommandTimeout":240}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"deviceName":"Android Emulator","app":"/Users/kazuaki/GitHub/python-client/test/apps/ApiDemos-debug.apk","platformName":"Android","newCommandTimeout":240},null,{"firstMatch":[{"appium:newCommandTimeout":240,"appium:app":"/Users/kazuaki/Git …
```

remove always_match and use first_match instead

---

README.md
test/functional/ios/desired_capabilities.py

This is an example to show how to handle port numbers to run tests in parallel. This will help users when they'd ike to run tests in parallel. The example has only two simulator case.
(This parallel running also help our test running.)
Run test in parallel as an example for parallel running #247 
```
$ python -m py.test -n 2 test/functional/ios/find_by_ios_class_chain_tests.py
=================================== test session starts ===================================
platform darwin -- Python 2.7.15, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
rootdir: /Users/kazu/GitHub/python-client, inifile:
plugins: xdist-1.23.0, forked-0.2
gw0 [2] / gw1 [2]
scheduling tests via LoadScheduling
..                                                                                  [100%] …
```

Add xdist port handling

---

appium/webdriver/webdriver.py
appium/webdriver/webelement.py
test/functional/android/appium_tests.py
test/functional/ios/appium_tests.py
test/functional/ios/desired_capabilities.py
test/functional/ios/find_by_element_webelement_tests.py

---
https://github.com/appium/appium/issues/10874#issuecomment-419973320
`driver.find_element/s_by_xxxx` works well. But `element.find_element/s_by_xxxx` doesn't since find selectors are converted to `css selector` by selenium-webdriver.

add find_elements w3c for webelement

---

appium/webdriver/webelement.py
setup.py
test/functional/ios/desired_capabilities.py

closes https://github.com/appium/python-client/issues/258
selenium 3.14.1 has workaround, calling JavaScript, for `get_attribute` and `is_displayed` in W3C.
In this PR, I override them in `webelement.py` to remove the workaround for Appium
I tested on my locale for each command.
```
Processing selenium-3.14.1-py2.py3-none-any.whl
Installing selenium-3.14.1-py2.py3-none-any.whl to /usr/local/lib/python2.7/site-packages
writing requirements to /usr/local/lib/python2.7/site-packages/selenium-3.14.1-py2.7.egg/EGG-INFO/requires.txt
Adding selenium 3.14.1 to easy-install.pth file
Installed /usr/local/lib/python2.7/site-packages/selenium-3.14.1-py2.7.egg
Searching for urllib3==1.23
Best match: urllib3 1.23
Adding urllib3 1.23 to easy-install.pth file
Using /usr/local/lib/python2.7/site-packages …
```

bump selenium 3.14.1, call RemoteCommand without workaround

---

appium/webdriver/webdriver.py
test/functional/ios/appium_tests.py

Method for _mobile: pressButton_ has been added.

Add an endpoint for pressing buttons

---

README.md
appium/webdriver/webdriver.py

Python 3 requires encoding in `bytes`. Python 2 doesn't.
close https://github.com/appium/python-client/issues/265
```
>>> driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
>>> driver.set_clipboard_text("hello")
>>> b = driver.get_clipboard()
>>> b.decode()
'hello'
>>> driver.set_clipboard_text("ありがとう")
>>> b = driver.get_clipboard()
>>> b.decode()
'ありがとう'
```
```
>>> driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
>>> driver.set_clipboard_text("ありがとう")
>>> b = driver.get_clipboard()
>>> print(unicode(b.decode('UTF-8')))
ありがとう
>>> driver.set_clipboard_text("hello")
>>> b = driver.get_clipboard()
>>> print(unicode(b.decode('UTF-8')))
hello
```

fix python3 set_clipboard error

---

appium/webdriver/webdriver.py

Python does not need to add parameters since options send to the server directly

append document for recording screen

---

test/functional/android/find_by_accessibility_id_tests.py

Issue:
There is no description provided for Animation label. Hence, appium is unable to locate the accessibility ID for Animation label. 
Solution:
Now, updated the label which has description and can be found the element by accessibility ID. So, all the tests find_by_accessibility_id_tests.py are getting passed.

Fixed failing tests in find_by_accessibility_id_tests.py

---

test/functional/android/appium_tests.py

There are 12 test cases failed in appium_tests.py. Fixed 4 test cases for now, that are listed below:
1. test_background_app
2. test_close__and_launch_app
3. test_reset
4. test_send_keys

Fixed few failing tests in appium_tests.py

---

test/unit/webdriver/touch_action_test.py

Add touch action unittest

---

appium/webdriver/extensions/activities.py
ci-requirements.txt
test/unit/webdriver/device/activities_test.py

Add activities unittest

---

test/unit/webdriver/device/device_time_test.py

Add devicetime unittest

---

appium/saucetestcase.py
test/unit/helper/test_helper.py
test/unit/webdriver/device/activities_test.py
test/unit/webdriver/device/clipboard_test.py
test/unit/webdriver/device/device_time_test.py
test/unit/webdriver/device/lock_test.py
test/unit/webdriver/device/network_test.py

Add a shortcut to decode `httpretty.last_request().body` with utf-8 in order to reduce writing `decode('utf-8')` everytime

Define httpretty last request body to wrap utf-8 decode

---

test/unit/webdriver/webdriver_test.py

An example of https://github.com/appium/python-client/issues/141 .
In Python, we can attach another session id if we override it with another session.
(Will link this to the issue.)

add a test case using another session id

---

README.md
appium/common/logger.py
appium/webdriver/webdriver.py
test/unit/webdriver/webdriver_test.py

This feature is the same as https://github.com/projectxyzio/web2driver#direct-connect-urls and https://www.rubydoc.info/github/appium/ruby_lib_core/Appium/Core/Driver#direct_connect-instance_method
Use case:
- If a user has a proxy server such as SeleniumGrid as below, an Appium client communicate with Appium servers via the proxy every command.
```
client <--> proxy server <---> appium server <-> devices
`-> appium server <-> devices
```
- Then, the communication takes additional seconds between the client and servers. The proxy server is if in the US and the Appium server is in Europ, the time increases more.
- To reduce the delay, we can distribute the proxy server to each reason, but it increases the complexity of the proxy server management.
- If we can make such communication …

Add direct connect flag to be able to handle directConnectXxxxc

---

appium/webdriver/webdriver.py
test/unit/webdriver/webdriver_test.py

Fix _RuntimeError: maximum recursion depth exceeded in cmp happened #342_
`self.__class__.__mro__` returns below:
> (<class 'webdriver_test.SubSubWebDriver'>, <class 'webdriver_test.SubWebDriver'>, <class 'appium.webdriver.webdriver.WebDriver'>, <class 'appium.webdriver.extensions.search_context.AppiumSearchContext'>, <class 'appium.webdriver.extensions.action_helpers.ActionHelpers'>, <class 'appium.webdriver.extensions.activities.Activities'>, <class 'appium.webdriver.extensions.applications.Applications'>, <class 'appium.webdriver.extensions.clipboard.Clipboard'>, <class 'appium.webdriver.extensions.context.Context'>, <class 'appium.webdriver.extensions.device_time.DeviceTime'>, <class 'appium.webdriver.extensions.hw_actions.HardwareActions'>, <class …

Fix RuntimeError: maximum recursion depth exceeded in cmp happened

---

appium/webdriver/appium_connection.py
appium/webdriver/webdriver.py

Selenium: https://github.com/SeleniumHQ/selenium/pull/7072/files
Java and .NET selenium client has been working as True.
The preference does not affect other features so we do not ristrict the selenium client version

make keep-alive True by default

---

appium/webdriver/extensions/gsm.py
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/unit/webdriver/device/device_time_test.py
test/unit/webdriver/device/gsm_test.py

Support set_gsm_signal

---

appium/webdriver/appium_service.py
test/unit/webdriver/appium_service_test.py

closes https://github.com/appium/python-client/issues/369
`httplib` is available only in Python 2 environment.
SImply, I replaced the http request checking with `PoolManager`.
I tested locally in both Python 2 and 3 env.
Added a simple test case to ensure it can load in both python 2 and 3 environments.

fix poll_url in Python 3

---

test/functional/android/appium_tests.py
test/functional/android/helper.py
test/functional/android/helper/test_helper.py

* Enable running tests on low performance device(e.g. emulator)
* test_screen_record
* test_set_text
* test_send_keys
* Enable running tests on Android P(9.0)
* test_update_settings
* "cyberdelia" doesn't exist in AndroidP at least.
* test_start_activity_other_app
* Changed app to be launched to avoid security exception
Verified with Python2/3 and emulator(AndroidP)
* Python2
```
Fix functional tests failed (android, appium_tests)
➜  android git:(fix-func-test-failed) ✗ python2 appium_tests.py
test_app_management (__main__.AppiumTests) ... ok
test_app_strings (__main__.AppiumTests) ... ok
test_app_strings_with_language (__main__.AppiumTests) ... ok
test_app_strings_with_language_and_file (__main__.AppiumTests) ... ok
test_background_app (__main__.AppiumTests) ... ok …
```

Fix functional tests failed (android, appium_tests)

---

test/functional/android/touch_action_tests.py

For https://github.com/appium/python-client/issues/373
1. Replaced ```find_element_by_name``` with ```find_element_by_accessibility_id```
1. Replaced "sleep and find_element" with ```wait_for_element```@ helper
1. Fix several value (mainly due to phone resolution, OS ver(?))
Verified with python2/3 and emulator(Nexus6, AndroidP)
```
➜  android git:(fix-test-touch-action) ✗ python2 touch_action_tests.py
test_drag_and_drop (__main__.TouchActionTests) ... ok
test_driver_drag_and_drop (__main__.TouchActionTests) ... ok
test_driver_swipe (__main__.TouchActionTests) ... ok
test_long_press (__main__.TouchActionTests) ... ok
test_long_press_x_y (__main__.TouchActionTests) ... ok
test_press_and_immediately_release (__main__.TouchActionTests) ... ok
test_press_and_immediately_release_x_y …
```

Fix functional tests failed (android, touch_action)

---

appium/webdriver/common/multi_action.py
test/functional/android/chrome_tests.py
test/functional/android/helper/test_helper.py
test/functional/android/ime_tests.py
test/functional/android/multi_action_tests.py

For https://github.com/appium/python-client/issues/373
Verified with Python2/3 and emulator(AndroidP) on https://github.com/appium/python-client/pull/372/commits/7c53fd31b4657932db7e55198efee3e02085f49f
* Python2/Python3
```
➜  android git:(fix-test-ime-multiaction) ✗ python2 ime_tests.py    
test_activate_ime_engine (__main__.IMETests) ... ok
test_active_ime_engine (__main__.IMETests) ... ok
test_available_ime_engines (__main__.IMETests) ... ok
test_deactivate_ime_engine (__main__.IMETests) ... ok
test_is_ime_active (__main__.IMETests) ... ok
----------------------------------------------------------------------
Ran 5 tests in 144.501s
OK
➜  android git:(fix-test-ime-multiaction) ✗ python3 ime_tests.py
test_activate_ime_engine (__main__.IMETests) ... ok
test_active_ime_engine …
```

Fix functional tests failed (android, ime/multi_action)

---

test/unit/webdriver/device/activities_test.py
test/unit/webdriver/device/lock_test.py

fixes https://travis-ci.org/appium/python-client/builds/533748403
They are not necessary to check.
sessionId is handled by MJSONWP mode. 
After https://github.com/appium/python-client/pull/382 , the driver will start as W3C mode. (expected behaviour)

Get rid of sessionId from some tests

---

appium/webdriver/webdriver.py

When we call `start_session()` on the webdriver we assign the w3c capabilities on the driver but not on the command_executor which then means that when we execute a command we do not remove the sessionId from the request which regresses from this change https://github.com/SeleniumHQ/selenium/commit/e6c2e7069c10852917846231439eeb807cd2e821.

Assign w3c property on the command executor.

---

appium/webdriver/extensions/android/gsm.py
appium/webdriver/extensions/android/network.py
appium/webdriver/mobilecommand.py
test/unit/webdriver/device/network_test.py

It's missing api support.
I've noticed by comparing below 2 files.
* https://github.com/appium/python-client/blob/master/appium/webdriver/mobilecommand.py
* https://github.com/appium/ruby_lib_core/blob/fd2cbde5466a144ce8dccfc6cf330b969bcc8fd3/lib/appium_lib_core/common/command/common.rb

Support set_network_speed

---

appium/webdriver/extensions/android/display.py
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/unit/webdriver/device/display.py

It's missing api support.
(It's the last one for now, I would say.)
I've noticed by comparing below 2 files.
* https://github.com/appium/python-client/blob/master/appium/webdriver/mobilecommand.py
* https://github.com/appium/ruby_lib_core/blob/fd2cbde5466a144ce8dccfc6cf330b969bcc8fd3/lib/appium_lib_core/common/command/common.rb

Support get_display_density

---

setup.py

When `Appium-Python-Client` is installed by `setup.py install`, `selenium4` is installed unexpectedly as resolving dependency.
It's problem when to setup environments on ci.
(But `pip install Appium-Python-Client` installs `selenium3` as resolving dependency.)
* Before
```
➜  python-client git:(fix-installed-selenium4) ✗ pip list
Package    Version
---------- -------
appdirs    1.4.3  
colorama   0.4.1  
pip        19.1.1 
setuptools 39.0.1 
➜  python-client git:(fix-installed-selenium4) ✗ python setup.py install                                                 
/Users/atsushimori/.pyenv/versions/3.7.1/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
warnings.warn(msg)
running install
(---snip---)
Searching for selenium>=3.14.1 …
```

Fix: installed selenium4 when 'setup.py install'

---

README.md
azure-pipelines.yml
ci-jobs/functional/run_appium.yml

For https://github.com/appium/python-client/issues/377

Run iOS functional tests on azure pipelines

---

azure-pipelines.yml
ci-jobs/functional/publish_test_result.yml
ci-jobs/functional_test.yml

For https://github.com/appium/python-client/issues/377

Publish functional test report

---

appium/webdriver/extensions/applications.py
appium/webdriver/webdriver.py

Move reset(self) method from webdriver.py to applications.py
This is in reference to #325 . Moved the reset app method from Webdriver.py to applications.py
Already test is added for this method in app_test.py

Moving reset method from WebDriver to Applications

---

README.md

For https://github.com/appium/python-client/issues/400

Add how to solve pipenv error to readme

---

appium/webdriver/extensions/execute_driver.py
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/functional/ios/execute_driver_tests.py
test/unit/webdriver/device/execute_driver_test.py

Waiting for https://github.com/appium/appium-base-driver/pull/328
Added _execute_driver_ as the new feature.
You can try the feature as `$ pytest test/functional/ios/execute_driver_tests.py` after applying the base driver PR on your local. I'll update this PR if something changes in the base driver PR.

Add execute driver

---

appium/webdriver/extensions/location.py
test/unit/webdriver/device/location_test.py

* Change altitude optional as arg for set_location
1. `altitude` is optional for appium server
- http://appium.io/docs/en/commands/session/geolocation/set-geolocation/
- JSON Parameters - altitude
2. It's enough that users set `altitude` when users want.
Checked below No.1-3 cases work.
```
self.driver.set_location(121.21, 11.56, 20)  # No.1
import time
time.sleep(10)
print(self.driver.location)
```
Link to https://github.com/appium/python-client/issues/414

Change altitude optional as arg for set_location

---

appium/webdriver/extensions/screen_record.py

Same as https://github.com/appium/java-client/pull/1180

Add videoFilters option documentation

---

.pre-commit-config.yaml
appium/webdriver/extensions/applications.py
ci.sh
test/unit/webdriver/device/location_test.py

* Fix: CI doesn't fail even if autopep8 makes changes
* Add `a` option to autopep8
* To reduce review comments for coding style
* https://github.com/hhatto/autopep8#more-advanced-usage
* `-a, --aggressive      enable non-whitespace changes; multiple -a result in more aggressive changes`

Fix: CI doesn't fail even if autopep8 makes changes

---

ci-jobs/functional/run_android_test.yml
ci-jobs/functional/run_appium.yml
ci-jobs/functional/run_ios_test.yml
ci-jobs/functional/save_appium_log.yml
ci-jobs/functional_test.yml
test/functional/android/activities_tests.py
test/functional/android/applications_tests.py
test/functional/android/chrome_tests.py
test/functional/android/device_time_tests.py
test/functional/android/find_by_accessibility_id_tests.py
test/functional/android/find_by_uiautomator_tests.py
test/functional/android/finger_print_tests.py
test/functional/android/helper/desired_capabilities.py
test/functional/android/helper/test_helper.py
test/functional/android/hw_actions_tests.py
test/functional/android/ime_tests.py
test/functional/android/keyboard_tests.py
test/functional/android/location_tests.py
test/functional/android/multi_action_tests.py
test/functional/android/network_connection_tests.py
test/functional/android/remote_fs_tests.py
test/functional/android/screen_record_tests.py
test/functional/android/settings_tests.py
test/functional/android/touch_action_tests.py
test/functional/android/webdriver_tests.py
test/functional/android/webelement_tests.py
test/functional/ios/execute_driver_tests.py

For https://github.com/appium/python-client/issues/377
* Basically wait for target elements located
* Extend various timeouts
* Others
* Run chrome, touch_action, multi_action, find_by_accessibility_id, find_by_uiautomator
10 times successes in a row
https://dev.azure.com/ki4070ma/python-client/_build?definitionId=2&_a=summary
* (success) 10/12
* https://dev.azure.com/ki4070ma/python-client/_build/results?buildId=414 to https://dev.azure.com/ki4070ma/python-client/_build/results?buildId=425
* Failures
* 1. Failed to launch android emulator.
* Launching emulator script is basically same to ruby_client's one based on azure's samples. Can't handle it.
* https://dev.azure.com/ki4070ma/python-client/_build/results?buildId=416
* 2. Lost communication with the server
* `The agent: Azure …

Fix android flaky tests

---

.isort.cfg
README.md
test/functional/android/activities_tests.py

I reproduced https://github.com/appium/python-client/pull/429#issuecomment-523845293 in my local. ( `mock` was handled as 1st party module.)
So this commit fixes isort behavior for `mock` as 3rd party module.

Fix isort behavior for mock

---

.travis.yml
test/functional/android/helper/test_helper.py
tox.ini

* https://travis-ci.org/appium/python-client/jobs/583237973
1. Already failing by https://github.com/appium/python-client/pull/433, but travis CI missed fails
2. https://github.com/appium/python-client/pull/431 outputs correct results
3. As a result that above 2 PRs merged, travis CI is failing
The combination with py3.8 and current pylint and astroid versions in `Pipfile` doesn't work

Fix CI fails

---

.isort.cfg
appium/saucetestcase.py
test/functional/ios/helper/desired_capabilities.py
test/functional/ios/safari_tests.py

CI failed due to below error log
```
E       selenium.common.exceptions.WebDriverException:
Message: An unknown server-side error occurred while processing the command.
Original error: Could not create simulator with name 'appiumTest-A651F479-95B0-47C8-9278-F71B25A780B6-iPhone 8',
device type id 'iPhone 8' and runtime id 'com.apple.CoreSimulator.SimRuntime.iOS-12-2'.
Reason: 'simctl error running 'create': Invalid runtime: com.apple.CoreSimulator.SimRuntime.iOS-12-2'
```
Upgraded iOS ver for simulator from 12.2 to 12.4

Fix CI fails (Updated iOS ver)

---

appium/webdriver/extensions/android/nativekey.py
test/unit/webdriver/nativekey_test.py

AndroidKey enum from java client ported. Instead of using unreadable numbers in code we can use these constant in order to write more readable code.

AndroidKey class for Key Codes added.

---

release.sh
script/release.py

If the python environment has no `twine`, an exception will occur. The command only pushes the dist module to pypi. (Building the  module is in another  method)
It can run after other tasks, so let me show a message to push later when the command fails.

chore: add try/catch in release script

---

.travis.yml
Pipfile
setup.py
tox.ini

For https://github.com/appium/python-client/issues/468
[Notes]
* Merge after April 2020
* Need check branch strategy
* `master` branch is for v1.0?
* Or create `v1.0` branch as feature branch?
* create `v0`(need better naming) as maintenance branch

Drop py2 support

---

appium/saucetestcase.py
appium/webdriver/appium_service.py
appium/webdriver/applicationstate.py
appium/webdriver/clipboard_content_type.py
appium/webdriver/common/multi_action.py
appium/webdriver/common/touch_action.py
appium/webdriver/connectiontype.py
appium/webdriver/extensions/android/display.py
appium/webdriver/extensions/android/gsm.py
appium/webdriver/extensions/android/network.py
appium/webdriver/extensions/clipboard.py
appium/webdriver/extensions/execute_driver.py
appium/webdriver/extensions/location.py
appium/webdriver/extensions/remote_fs.py
appium/webdriver/extensions/search_context/base_search_context.py
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/functional/android/common_tests.py
test/functional/android/ime_tests.py
test/functional/android/log_event_tests.py
test/functional/android/webelement_tests.py
test/functional/ios/helper/desired_capabilities.py
test/functional/ios/webdriver_tests.py
test/functional/test_helper.py
test/unit/helper/test_helper.py
test/unit/webdriver/webdriver_test.py

* Used `f'This is {item}'` instead of `'This is {}'.format(item)` for some cases.
* Removed unnecessary `(object)` from class definitions.
* Removed unused imports

chore: Applied some py3 formats

---

appium/webdriver/common/mobileby.py
appium/webdriver/extensions/search_context/android.py
test/functional/android/search_context/find_by_view_matcher_tests.py

For https://github.com/appium/appium/issues/13747

feat: Add viewmatcher

---

ci-jobs/functional_test.yml
test/functional/android/applications_tests.py
test/functional/android/common_tests.py
test/functional/android/context_switching_tests.py
test/functional/android/multi_action_tests.py
test/functional/android/network_connection_tests.py
test/functional/android/search_context/find_by_accessibility_id_tests.py
test/functional/android/search_context/find_by_image_tests.py
test/functional/android/search_context/find_by_uiautomator_tests.py
test/functional/android/touch_action_tests.py

For https://github.com/appium/python-client/issues/472

Fix flaky functional tests

---

appium/webdriver/appium_service.py
appium/webdriver/errorhandler.py
appium/webdriver/extensions/remote_fs.py

For https://github.com/appium/python-client/issues/468
[Reference]
* https://docs.python.org/3.8/library/exceptions.html
* https://docs.python.org/3/reference/simple_stmts.html#the-raise-statement

Add 'from' to 'raise exception'

---

appium/webdriver/appium_connection.py

https://github.com/appium/java-client/pull/1327

feat: Add idempotency key header to create session requests

---

appium/webdriver/webelement.py
test/functional/ios/keyboard_tests.py
test/unit/webdriver/webelement_test.py

Will update the naming, but let me create a PR as a draft
background: https://github.com/appium/appium-desktop/issues/1335
`send_keys` by some selenium bindings send a local file binary if the given string is a file.
But https://github.com/appium/appium-desktop/issues/1335 has a use case won't send a local file even if the given string is a local path.

feat: Override send_keys without file upload function

---

README.md
test/functional/ios/helper/desired_capabilities.py

For #373 
1. Fix for below error in ios desired_capabilities, which occurred when trying to run ios functional tests in parallel
```
if number >= PytestXdistWorker.COUNT:
TypeError: '>=' not supported between instances of 'int' and 'str'
```
2. Updated test case folder path and iPhone model in Readme file
```
(appium-dev) akvenk:search_context akvenk$ pytest -n 2 find_by_ios_class_chain_tests.py 
bringing up nodes...
..                                                                                                                                                                                                                              [100%]Coverage.py warning: Module appium was never imported. (module-not-imported)
Coverage.py warning: No data was collected. (no-data-collected) …
```

chore: Fix int - str comparison error in ios desired capabilities

---

appium/webdriver/webelement.py
test/unit/webdriver/webelement_test.py

- Add additional type check to ```get_attribute()``` to avoid mishandling of dictionaries received from an Appium server.
get_attribute() in WebElement currently cannot receive dictionary values.
E.g. when calling ```get_attribute('rect')``` on an element the Appium iOS Server returns a dictionary of coordinates and size which the Python client cannot handle:
```
>>> buttons[2].get_attribute('rect')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.7/site-packages/appium/webdriver/webelement.py", line 66, in get_attribute
attributeValue = unicode(attributeValue)
NameError: name 'unicode' is not defined
```
*(Note that the NameError results from me using Python 3 in which ```unicode()``` is not available. I am not sure whether this should …

fix: Handling of dictionary-values in WebElement.get_attribute()

---

.gitchangelog.rc
CHANGELOG.rst
README.md

- Addressed _1.0.0 will drop Python 2.0 support_ in README 
- Update changelog logic
---
I searched if the gitchangelog could insert an arbitrary line which was not in git log, but it seemed no. https://github.com/appium/python-client/pull/522/files#r415238307
So, let me leave a line about it. 
I also tweaked gitchangelog section role.

chore: Update readme and gitchangelog section role

---

LICENSE
README.md

We're going to switch documentation with https://github.com/appium/python-client-sphinx, so description in README is removable.
I also correct LICENSE to fit Apach 2 (copied from appium/appium)

docs: Update documentation

---

setup.py

`py.typed` is missing in package.
Current master hasn't pushed yet.
I noticed the missing item when I crated a package on my local
https://github.com/appium/python-client/issues/537
I also added maintainer part

chore: add py.typed in package, add maintainers

---

setup.py

Manually installed by `python setup.py install` on local package, then all files were in `build/lib/appium/**`
We can check the package with:
1. `python setup.py sdist`
2. Go to `dist/<package>`
3. `python setup.py install`
4. Check the number of files in ``build/lib/appium/**`
Let me add the package check in release script.

fix: broken package

---

release.sh
script/release.py

It help to prevent broken package like https://github.com/appium/python-client/issues/542 without any expensive process.

chore: add checking package file count comparison in release script

---

.pre-commit-config.yaml
.travis.yml
Makefile
Pipfile
ci.sh
setup.cfg
tox.ini

And upgraded used module versions.
python3.9 will come soon. https://www.python.org/dev/peps/pep-0596/#release-schedule

ci: Added py39-dev for travis

---

README.md

@ki4070ma Hi,
Our Azure team includes this repository now https://dev.azure.com/AppiumCI/Appium%20CI/_build?definitionId=56&_a=summary 
Could you disable your https://dev.azure.com/ki4070ma/python-client ?

ci: move azure project to Appium CI

---

README.md

I've created a selenium-4 based branch to inherits selenium 4.0.0.a7 (for now) instead of current v3.
It allows us to relax SSL verification so that it can connect to self-certificated SSL server.
I'd like to push the branch as pre-release like `2.0.0.a0` to pipy like selenium 4.0.0.a7.
For now, Python 3 and selenium v3 cannot connect to the environment because of an exception.
Our main working branch is still v1 (current master) though.
---
Btw, Python binding v4 still has JSONWP as well, while selenium 4 is basically going to support only W3C

chore: address selenium-4 branch in readme

---

appium/webdriver/webdriver.py
test/unit/webdriver/webdriver_test.py

`forceMjsonwp` only sends MJSONWP formatted capabilities, but selenium 4 and Appium is already going to focus on W3C.
The initial motivation to allow forceMjsonwp was to help users so that they were able to move to W3C from MJSONWP in their timeline. chrome driver also already defaults to W3C spec, so it's a good time to drop it.

feat: add warning to drop forceMjsonwp for W3C

---

ci-jobs/functional_test.yml
test/functional/ios/helper/desired_capabilities.py
test/functional/ios/keyboard_tests.py

Failed functional keyboard tests with appium v1.21.0-beta.0
Link: https://github.com/appium/python-client/issues/570#issuecomment-766890824
Failing below TC (Does these failures come from upgrading xocde and target iOS?)
Test results with iOS 13.6
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=13648&view=results

chore: Fix functional keyboard tests with appium v1.21.0-beta.0

---

.pre-commit-config.yaml
Makefile
Pipfile
appium/webdriver/common/multi_action.py
appium/webdriver/common/touch_action.py
test/functional/android/helper/test_helper.py
test/unit/helper/test_helper.py

Since isort v4 is used.
Currently mypy target is only `functional` under `test.`( `test/unit` is ignored by mypy v0.782 somehow.)
(But in my opinion, it isn't so impact even if `test/unit` is not target.)

chore: Update pipfile to respect isort v5

---

appium/webdriver/extensions/screen_record.py
test/functional/android/appium_service_tests.py
test/functional/android/common_tests.py
test/functional/android/helper/test_helper.py
test/functional/android/multi_action_tests.py
test/functional/android/search_context/find_by_accessibility_id_tests.py
test/functional/android/search_context/find_by_image_tests.py
test/functional/android/touch_action_tests.py
test/functional/android/webelement_tests.py
test/functional/mac/execute_script_test.py
test/functional/mac/helper/desired_capabilities.py
test/functional/mac/helper/test_helper.py
test/functional/mac/webelement_test.py
test/functional/test_helper.py

from https://github.com/appium/java-client/pull/1439
Added functional tests for macOS (from https://github.com/appium/appium-mac2-driver#examples )

feat: Added docstring for macOS screenrecord option

---

CHANGELOG.rst
appium/version.py
appium/webdriver/webdriver.py

This PR is for selenium-4 branch.
Fixes https://github.com/appium/python-client/issues/597 for selenium-4 branch.
(This PR also includes bumped python client version I forgot to merge to selenium-4 branch.
Main change is only in appium/webdriver/webdriver.py

fix: remove w3c argument in MobileWebElement

---

appium/webdriver/command_method.py
appium/webdriver/webdriver.py
test/unit/webdriver/webdriver_test.py

Appium 2.0 will allow custom drivers/plugins add their own endpoint.
Then, we want to allow clients to add custom commands for them.
In Ruby, I've added like https://github.com/appium/ruby_lib_core/blob/b9f015d7dea14964a0733f2385ebcff68da1e18e/test/unit/android/webdriver/w3c/commands_test.rb#L31-L98 as an experimental method. (The method was already used internally, so as Ruby client, it was just exposed the method as a public method.)
In Python, I've added two methods. `add_command` and `execute_custom_command`.
`add_command` adds the pair of HTTP method and a path in `self.command_executor._commands`.
`execute_custom_command` calls a method from `self.command_executor._commands` as `self.execute`.
We want to hide `self.execute` and `self.command_executor` since they are for internal …

feat: allow to add a command dynamically

---

CHANGELOG.rst
README.md
appium/webdriver/common/multi_action.py
appium/webdriver/common/touch_action.py
appium/webdriver/extensions/action_helpers.py
appium/webdriver/webdriver.py

closes https://github.com/appium/python-client/issues/647
- Do tests have them?

chore: adding deprecation mark in touch actions and multi touch

---

ci-jobs/functional/run_appium.yml
tox.ini

The below error started last readme update.  let me run this...
```
[ResolutionFailure]:   File "/home/vsts/work/1/s/.tox/py/lib/python3.7/site-packages/pipenv/resolver.py", line 743, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
[ResolutionFailure]:   File "/home/vsts/work/1/s/.tox/py/lib/python3.7/site-packages/pipenv/resolver.py", line 711, in resolve_packages
[ResolutionFailure]:       requirements_dir=requirements_dir,
[ResolutionFailure]:   File "/home/vsts/work/1/s/.tox/py/lib/python3.7/site-packages/pipenv/resolver.py", line 693, in resolve
[ResolutionFailure]:       req_dir=requirements_dir
[ResolutionFailure]:   File "/home/vsts/work/1/s/.tox/py/lib/python3.7/site-packages/pipenv/utils.py", line 1377, in …
```

ci: set pipenv==2021.5.29 to prevent dependencies error

---

appium/webdriver/extensions/search_context/android.py
appium/webdriver/extensions/search_context/custom.py
appium/webdriver/extensions/search_context/ios.py
appium/webdriver/extensions/search_context/mobile.py
appium/webdriver/webdriver.py
appium/webdriver/webelement.py

Part of https://github.com/appium/python-client/issues/645
It looks like we've recommended to use `find_element_by_*` instead of vanilla `fine_element(xxx)`, so let's print deprecated message first (and for a while)

chore: add deprecated mark for find_element_by*

---

appium/webdriver/common/appiumby.py
appium/webdriver/common/mobileby.py
appium/webdriver/common/multi_action.py
appium/webdriver/common/touch_action.py
appium/webdriver/extensions/search_context/android.py
appium/webdriver/extensions/search_context/custom.py
appium/webdriver/extensions/search_context/ios.py
appium/webdriver/extensions/search_context/mobile.py
appium/webdriver/extensions/search_context/windows.py
appium/webdriver/webdriver.py
appium/webdriver/webelement.py
test/functional/android/appium_service_tests.py
test/functional/android/common_tests.py
test/functional/android/multi_action_tests.py
test/functional/android/search_context/find_by_accessibility_id_tests.py
test/functional/android/search_context/find_by_image_tests.py
test/functional/android/search_context/find_by_view_matcher_tests.py
test/functional/android/touch_action_tests.py
test/functional/android/webelement_tests.py
test/functional/mac/execute_script_test.py
test/functional/mac/webelement_test.py
test/functional/test_helper.py

part of https://github.com/appium/python-client/issues/645

feat: add AppiumBy instead of MobileBy

---

README.md
appium/webdriver/extensions/action_helpers.py
appium/webdriver/extensions/search_context/android.py
appium/webdriver/webdriver.py

For https://github.com/appium/python-client/issues/667#issuecomment-1000146316
By default, python clients set `mouse` mode. I guess it could be `touch`.

feat: use 'touch' pointer action

---

Pipfile
setup.py

https://github.com/appium/appium/issues/16503
Selenium 4.1 dropped non-w3c commands, while still appium client needs them.

chore: restrict selenium client version

---

Pipfile
ci.sh

It looks like pylint cannot properly parse the module source and thus throws many false positives

chore: Disable pylint checks fail CI

---

appium/options/android/__init__.py
appium/options/android/uiautomator2/base.py
appium/options/common/__init__.py
appium/options/common/automation_name_option.py
appium/options/common/base.py
appium/options/common/platform_name_option.py
appium/options/common/supports_capabilities.py
appium/options/ios/__init__.py
appium/options/ios/xcuitest/base.py
appium/options/mac/__init__.py
appium/options/mac/mac2/base.py
appium/webdriver/webdriver.py
test/functional/android/helper/test_helper.py
test/functional/ios/helper/test_helper.py
test/functional/mac/helper/test_helper.py
test/unit/helper/test_helper.py
test/unit/webdriver/webdriver_test.py

This is just POC to demonstrate my vision for W3C Options support in Python client. 
If we accept it then it would be necessary to add all the supported capabilities like we did in Java, although this could be done gradually in multiple PRs.

feat: Add support for w3c options

---

appium/webdriver/extensions/action_helpers.py

- Fixed handling the duration argument in swipe() and scroll() helpers
- Functionality is now the same as in older versions using TouchActions
Fixes #743

fix: Backwards compatible behaviour of swipe and scroll in action_helpers

---

appium/options/android/common/adb/adb_exec_timeout_option.py
appium/options/android/common/app/android_install_timeout_option.py
appium/options/android/common/app/app_wait_duration_option.py
appium/options/android/common/avd/avd_launch_timeout_option.py
appium/options/android/common/avd/avd_ready_timeout_option.py
appium/options/android/common/context/auto_webview_timeout_option.py
appium/options/android/common/locking/unlock_success_timeout_option.py
appium/options/android/espresso/espresso_server_launch_timeout_option.py
appium/options/android/uiautomator2/uiautomator2_server_install_timeout_option.py
appium/options/android/uiautomator2/uiautomator2_server_launch_timeout_option.py
appium/options/android/uiautomator2/uiautomator2_server_read_timeout_option.py
appium/options/common/new_command_timeout_option.py
appium/options/ios/xcuitest/app/app_push_timeout_option.py
appium/options/ios/xcuitest/other/command_timeouts_option.py
appium/options/ios/xcuitest/simulator/simulator_startup_timeout_option.py
appium/options/ios/xcuitest/wda/wait_for_idle_timeout_option.py
appium/options/ios/xcuitest/wda/wda_connection_timeout_option.py
appium/options/ios/xcuitest/wda/wda_eventloop_idle_delay_option.py
appium/options/ios/xcuitest/wda/wda_launch_timeout_option.py
appium/options/ios/xcuitest/wda/wda_startup_retry_interval_option.py
appium/options/ios/xcuitest/webview/webkit_response_timeout_option.py
appium/options/ios/xcuitest/webview/webview_connect_timeout_option.py
appium/options/mac/mac2/server_startup_timeout_option.py
appium/options/windows/windows/create_session_timeout_option.py
appium/options/windows/windows/wait_for_app_launch_option.py

It turns out timedelta class normalises its seconds, microseconds and days properties as mentioned in https://docs.python.org/3/library/datetime.html#datetime.timedelta
Thus we need to use the total_seconds() property in order to avoid unexpected normalization side effects in case longer deltas are provided

fix: Use total_seconds property of timedelta

---

Pipfile
tox.ini

Related to https://github.com/appium/python-client/issues/771

fix: Move dev-only dependencies to [dev-packages] section

---

.pre-commit-config.yaml

https://github.com/pre-commit/mirrors-isort is archived. The readme mentioned to use https://github.com/PyCQA/isort directly.
```
[INFO] Initializing environment for https://github.com/PyCQA/isort.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] …
```

chore: update precommit

---

appium/webdriver/webdriver.py
appium/webdriver/webelement.py
test/unit/webdriver/webelement_test.py

`set_text` and `set_value` would not work, without these changes, on the latest beta56 of Appium.
These are the values that Appium corrected me with, that I have replaced in the code.
Is there any place where one would validate the parameters that should be sent? Either some documentation, or a reference library?
EDIT: is this the reference to use? https://w3c.github.io/webdriver/#element-send-keys

fix: set_value and set_text sent incorrect data

---

README.md
appium/webdriver/appium_connection.py
appium/webdriver/webdriver.py
test/unit/webdriver/webdriver_test.py

Got a request to use the given executor if the first argument was the instance as same as Selenium does.
Example usage is in the README.

feat: respect the given executor

---

appium/webdriver/errorhandler.py

It turns out the current selenium python client does not match error codes properly, at least for W3C responses.

fix: W3C errors to exception classes mapping

---

.github/workflows/unit-test.yml
README.md
setup.py

To prevent unexpected changes that could break this client's functionality.
Actually, the last break was by a patch version, but maybe it is reasonable to set the limit in the minor version for now.

docs: address version management recommendation in the readme

---

Pipfile
appium/webdriver/webdriver.py

Addresses https://github.com/appium/python-client/issues/878

fix: Update the constructor for compatibility with python client 4.10

---

.pre-commit-config.yaml

using `isort` revision 5.10.1 raise an error when trying to commit a change:
```
line 58, in create_poetry
raise RuntimeError("The Poetry configuration is invalid:\n" + message)
RuntimeError: The Poetry configuration is invalid:
- [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
[end of output]
```
once I updated `isort` to 5.12.0, the error is gone.

chore: update isort revision to 5.12.0

---

.pre-commit-config.yaml

Ran `pre-commit autoupdate`. Pipfile.lock has the same version.
I wondered if we could sync the rev and Pipfile.lock, but probably no good way...?

chore: run pre-commit autoupdate

---

.pre-commit-config.yaml
test/functional/android/applications_tests.py

Currently, when trying to commit, mypy hook is failing on `Library stubs not installed for "dateutil.parser"` although they are installed.
```
(venv) E:\Git\python-client>mypy --python-executable venv\Scripts\python --install-types
Installing missing stub packages:
venv\Scripts\python -m pip install types-python-dateutil
Install? [yN] y
Requirement already satisfied: types-python-dateutil in e:\git\python-client\venv\lib\site-packages (2.8.19.13)
```
The solution I found, for now, is adding additional_dependencies to mypy .pre-commit hook
See https://github.com/dateutil/dateutil/issues/383 for more info

fix: Add missing dependencies for types-python-dateutil

---

appium/webdriver/errorhandler.py

In my tests the payload was always of string type, but such approach should be safer anyway

fix: Handle the situation where payload is already a dictionary

---

README.md

I saw a couple of times about this `options` argument report these days. Lets address it in the migration guide since v3 completely removed the old desired_capabilities

docs: address options in the migration guide

---

appium/webdriver/webdriver.py
test/unit/webdriver/webdriver_test.py

The new replaced instance was always `RemoteConnection`, which was not Appium's one. Use AppiumConnection if the executor was already made by AppiumConnection

fix: self.command_executor instance in _update_command_executor

---

README.md
appium/webdriver/common/multi_action.py
appium/webdriver/common/touch_action.py

http://appium.io/docs/en/commands/interactions/actions/ returns 404.
selenium documentation has actions api right now. This lib's README has `MultiAction/TouchAction to W3C actions` thus at least we can replace the 404 link to the README.
cc @Dor-bl

docs: update links

---

appium/webdriver/common/multi_action.py

For https://github.com/appium/python-client/pull/963
The usage addressed `MultiAction(driver).add(a1, a2).perform()` usage in the docstring, thus return self is probably correct way for this `add` as well.

fix: add return self in MultiAction#add

---

appium/webdriver/extensions/action_helpers.py

closes https://github.com/appium/python-client/issues/955

feat: add pause in drag_and_drop

---

appium/webdriver/appium_service.py

https://github.com/appium/python-client/issues/962
After self._process.terminate() a call to Popen.communicate()](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate) shall be made, which will close the file handles.
This will ensure that file stdout and sdterr file descriptors are closed properly.

fix: unclosed file <_io.BufferedReader name error by proper cleanup of subprocess.Popen process

---

appium/webdriver/common/appiumby.py
appium/webdriver/webdriver.py

The objective of this PR is to remove the IOS_UIAUTOMATION locator, which is deprecated.
closes https://github.com/appium/python-client/issues/913
BREAKING: remove obsolete IOS_UIAUTOMATION

chore: remove IOS_UIAUTOMATION

---

.github/functional-test.yml

I'm working on Azure replacement with newer macOS env on gha. This PR is to run tests by manual kick, so let me merge this right now.
A followup PR will have more updates after running tests.

ci: add initial gha to run by manual

---

appium/webdriver/extensions/clipboard.py
test/unit/webdriver/device/clipboard_test.py

Similar to https://github.com/appium/java-client/pull/2188

chore: Add mobile: replacements to clipboard API wrappers

---

README.md

We moved to GHA, so the badge also can be the https://github.com/appium/python-client/actions/workflows/functional-test.yml

docs: replace badge source

---

appium/options/mac/mac2/app_path_option.py
appium/options/mac/mac2/base.py

This PR adds support for setting the optional appPath capability via Mac2Options().app_path, aligning with the related "bundle_id" setting. Presently it is necessary to pass in a value for appPath as part of the capabilities dictionary to Mac2Options().load_capabilities() if you wish to set it.
appPath is implemented in the Mac2 driver:
https://github.com/appium/appium-mac2-driver?tab=readme-ov-file#capabilities

feat: add app_path property ("appPath") to Mac2Options

---

appium/webdriver/extensions/flutter_integration/__init__.py

To fix packaging:
```
The count of files in 'appium' and 'build/lib/appium' were different.
'appium' has '{'/webdriver/extensions/flutter_integration/flutter_commands.py', '/webdriver/extensions/flutter_integration/scroll_directions.py', '/webdriver/extensions/flutter_integration/flutter_finder.py'}' files than build/lib/appium
Python files in 'build/lib/appium' may differ from 'appium'. Please make sure setup.py is configured properly.
```

fix: add missing __init__.py

---

appium/webdriver/appium_service.py

Also sorted module-private methods and aligned service url parsing logic

feat: Add a separate function for service startup validation

---

.pre-commit-config.yaml
Pipfile

instead of https://github.com/appium/python-client/pull/1041
The pre-commit v3.5.0 can work with python 3.8

chore: update pre-commit

---

test/unit/webdriver/app_test.py

use pytest without class-based structures, using parameterization for better reusability.
Partly address https://github.com/appium/python-client/issues/644

test: Move `app_test.py` to pytest style

---

test/unit/webdriver/log_test.py

Partly address https://github.com/appium/python-client/issues/644

test: Move `log_test.py` to pytest style

---

appium/webdriver/webdriver.py

When initializing a webdriver with appium/python-client version 4.5.0, I get a warning log.
```2.16.2```
```4.5.0```
```8.3.4```
```
APPIUM_PORT = 4723
APPIUM_HOST = '127.0.0.1'
client_config = ClientConfig(
remote_server_addr="http://127.0.0.1:4723", 
ignore_certificates=True
)
@pytest.fixture(scope='session')
def appium_service():
service = AppiumService()
service.start(
args=['--address', APPIUM_HOST, '-p', str(APPIUM_PORT)],
timeout_ms=20000,
)
yield service
service.stop()
def create_ios_driver(custom_opts = None):
options = XCUITestOptions()
options.platformVersion = '18.2'
options.udid = 'FCD6B2FA-5C83-4069-82A4-76CE581CB1E3'
options.no_reset = True
if custom_opts is not None:
options.load_capabilities(custom_opts)
return webdriver.Remote(f'http://{APPIUM_HOST}:{APPIUM_PORT}', …
```

fix: prevent warning log when initialize a webdriver using version 4.5.0 (selenium v4.26+)

---

appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py

They have already been removed.

chore: remove unused commands

---

appium/options/android/common/adb/logcat_filter_specs_option.py
appium/webdriver/extensions/android/nativekey.py
appium/webdriver/extensions/execute_driver.py
appium/webdriver/webelement.py

refactor: fix typos

---

.github/workflows/functional-test.yml
test/functional/ios/helper/desired_capabilities.py

https://github.com/appium/python-client/issues/1140

ci: apply prebuilt wda

---

appium/webdriver/common/appiumby.py
appium/webdriver/extensions/android/activities.py
appium/webdriver/extensions/flutter_integration/flutter_commands.py
appium/webdriver/extensions/flutter_integration/flutter_finder.py
appium/webdriver/webdriver.py
appium/webdriver/webelement.py

Fixes some mypy errors.
- Add `# type: ignore[override]` to ignore incompatible type errors because of our lirbary's override to let users chain methods
- Add `type: ignore[arg-type]` for ignorable errors for selenium lib
- Add `find_element` and `find_elements` for typehint usage
- The actual implementation returns the given `web_element_cls=MobileWebElement` so they are necessary only for typehint
After
```
appium/webdriver/switch_to.py:29: error: Definition of "_driver" in base class "SwitchTo" is incompatible with definition in base class "HasDriver"  [misc]
```
Before
```
$ mypy appium 
appium/webdriver/extensions/flutter_integration/flutter_finder.py:33: error: Argument 1 to "FlutterFinder" has incompatible type "str"; expected "Literal['id', 'xpath', 'link text', 'partial link …
```

chore: fix some mypy errors
