appium/python-client

appium/__init__.py
appium/saucetestcase.py

So there is a simple way to use the client with Sauce.

Add base class for Sauce tests

---

appium/webdriver/webdriver.py

Fix start_activity for Python3

---

appium/webdriver/webdriver.py

Found a easier way to implement `wait_activity` method: using selenium `WebDriverWait`

modify the implementation of wait_activity method

---

appium/webdriver/common/touch_action.py

Revert changes made earlier. Change on the server instead, so client can be used on all versions of Appium.

Revert actions change

---

appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/functional/android/appium_tests.py

Add device_time property

---

appium/webdriver/webdriver.py
appium/webdriver/webelement.py

The server expects id only.
I fixed this server-side, but this will be quicker. 
See #129

Use id instead of elementId

---

appium/webdriver/clipboard_content_type.py
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py

See https://github.com/appium/java-client/pull/855 for more details

Add clipboard handlers

---

appium/webdriver/common/touch_action.py

Addresses https://github.com/appium/python-client/issues/213

Avoid setting coordinates to null for touch actions

---

appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py

Based on https://github.com/appium/appium-base-driver/pull/203

Add wrappers for OpenCV-based image comparison

---

appium/webdriver/webdriver.py

It's useful to have it there along with the documentation.

Add an endpoint for getting battery info

---

appium/webdriver/webdriver.py

Based on https://github.com/appium/appium-base-driver/pull/208

Add flags argument to press_keycode

---

README.md

- Tweak some PyPi URLs
- Add a badge which version is available from PyPi to catch up with the latest version

tweak PyPi URLs and add a badge

---

.github/issue_template.md

I noticed this repository has no this kind of template...

add a github issue template

---

appium/webdriver/common/mobileby.py
appium/webdriver/webdriver.py

as a result of https://github.com/appium/appium-base-driver/pull/268

add custom locator strategy

---

ci-requirements.txt

Updated requirements.txt file with version number for all the libraries

Updated requirements.txt file with version

---

test/unit/webdriver/device/lock_test.py

Add unit test for lock lib

---

.gitignore
.travis.yml
README.md
ci-requirements.txt
script/__init__.py
test/unit/webdriver/device/lock_test.py
tox.ini

run with tox on travis

---

appium/webdriver/extensions/context.py
appium/webdriver/extensions/location.py
appium/webdriver/webdriver.py
setup.py
test/unit/webdriver/device/context_test.py

related to https://github.com/appium/python-client/pull/291/files, https://github.com/appium/python-client/issues/295
- Ensured it loads correctly defining `context_test.py`
- Added an `extensions` package introduced in #291 to publish it via pypi

Add package and a test

---

setup.py

reference: https://packaging.python.org/guides/making-a-pypi-friendly-readme
Tested at https://pypi.org/project/delayed-assert

Fixing broken pypi long description rendering

---

test/unit/webdriver/device/context_test.py
test/unit/webdriver/device/lock_test.py
test/unit/webdriver/device/settings_test.py
test/unit/webdriver/webdriver_test.py

For https://github.com/appium/python-client/issues/283

Add settings unittest

---

appium/webdriver/webdriver.py
test/unit/webdriver/device/keyboard_test.py

Why move class Keyboard to extension but not inherit it ? #318

import keyboard, add tests

---

appium/webdriver/appium_connection.py
appium/webdriver/webdriver.py
test/unit/webdriver/webdriver_test.py

https://github.com/appium/appium/issues/4065

add AppiumConnection to customise user agent

---

appium/webdriver/extensions/screen_record.py

Addresses https://github.com/appium/python-client/issues/329

Fix passing options to screen record commands

---

appium/webdriver/extensions/location.py
test/unit/webdriver/device/location_test.py

Addresses https://github.com/appium/python-client/issues/331

Cast set_location arguments to float

---

appium/common/helper.py
script/release.py
test/unit/webdriver/webdriver_test.py

after run `setup.py sdist` and unzip the package:
```
>>> import appium.common.helper as h
>>> h.library_version()
'0.36'
```
https://github.com/appium/python-client/issues/333

remove io.open from getting version code

---

test/unit/webdriver/device/shake_test.py

Add shake unittest

---

test/unit/webdriver/device/fingerprint_test.py

Add fingerprint unittest

---

appium/webdriver/extensions/screen_record.py

https://github.com/appium/appium-xcuitest-driver/pull/896/files

Add pixelFormat in docstring

---

appium/webdriver/extensions/settings.py
appium/webdriver/webdriver.py

https://github.com/appium/python-client/issues/325

Move settings to mixin classes

---

appium/webdriver/extensions/sms.py
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/unit/webdriver/device/sms_test.py

For https://github.com/appium/python-client/issues/350

Support send sms

---

test/functional/android/find_by_image_tests.py
test/unit/webdriver/device/settings_test.py

True/False in https://github.com/appium/appium/blob/c9a9aa354e203cc8d8c869bae0947aff328f3f01/docs/en/advanced-concepts/image-elements.md should be boolean

Fix True/False in image settings, add boolean value in settings test

---

appium/webdriver/extensions/device_time.py
appium/webdriver/extensions/power.py
appium/webdriver/extensions/sms.py
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/unit/webdriver/device/app_test.py
test/unit/webdriver/device/keyboard_test.py
test/unit/webdriver/device/location_test.py
test/unit/webdriver/device/network_test.py
test/unit/webdriver/device/power_test.py
test/unit/webdriver/device/settings_test.py
test/unit/webdriver/device/shake_test.py
test/unit/webdriver/device/sms_test.py

Support set_power_capacity and set_power_ac

---

appium/webdriver/extensions/system_bars.py
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/unit/webdriver/device/system_bars_test.py

Support get_system_bars

---

appium/webdriver/extensions/gsm.py
appium/webdriver/mobilecommand.py
test/unit/webdriver/device/gsm_test.py

Support set_gsm_voice

---

appium/webdriver/extensions/device_time.py
appium/webdriver/extensions/gsm.py
appium/webdriver/extensions/performance.py
appium/webdriver/extensions/power.py
appium/webdriver/extensions/sms.py
appium/webdriver/extensions/system_bars.py
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/unit/webdriver/device/performance_test.py

Support get_performance_data, get_performance_data_types

---

test/unit/webdriver/device/lock_test.py
test/unit/webdriver/webdriver_test.py

- Add assertions for `command_executor.w3c`
- Fix a failing test

add assertions for command_executor.w3c

---

appium/common/exceptions.py
appium/common/helper.py
appium/webdriver/appium_service.py
appium/webdriver/common/multi_action.py
appium/webdriver/common/touch_action.py
appium/webdriver/extensions/action_helpers.py
appium/webdriver/extensions/android/activities.py
appium/webdriver/extensions/android/display.py
appium/webdriver/extensions/android/gsm.py
appium/webdriver/extensions/android/network.py
appium/webdriver/extensions/android/performance.py
appium/webdriver/extensions/android/power.py
appium/webdriver/extensions/android/sms.py
appium/webdriver/extensions/android/system_bars.py
appium/webdriver/extensions/applications.py
appium/webdriver/extensions/clipboard.py
appium/webdriver/extensions/context.py
appium/webdriver/extensions/device_time.py
appium/webdriver/extensions/hw_actions.py
appium/webdriver/extensions/images_comparison.py
appium/webdriver/extensions/ime.py
appium/webdriver/extensions/keyboard.py
appium/webdriver/extensions/location.py
appium/webdriver/extensions/remote_fs.py
appium/webdriver/extensions/screen_record.py
appium/webdriver/extensions/search_context.py
appium/webdriver/extensions/settings.py
appium/webdriver/switch_to.py
appium/webdriver/webdriver.py
appium/webdriver/webelement.py

For https://github.com/appium/python-client/issues/387
* Reference
* https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
* https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
* https://stackoverflow.com/questions/1137161/what-is-the-correct-way-to-document-a-kwargs-parameter
* https://github.com/google/mobly

Use the same format for docstring

---

test/unit/webdriver/device/notifications_test.py

add unit test for open_notifications

---

appium/webdriver/webdriver.py
ci-jobs/functional_test.yml

For https://github.com/appium/python-client/issues/402
It's another topic which type of docstring is better. > pycharm typehinting, google, numpy.

Add autocompletion for pycharm

---

appium/webdriver/appium_service.py

Bytes need to be decoded first before joining

Bug fix joining path in _get_main_script

---

test/unit/webdriver/device/remote_fs_test.py

For https://github.com/appium/python-client/issues/283

Add remote_fs unittest

---

Pipfile
appium/version.py
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/unit/webdriver/webdriver_test.py

COPY OF https://github.com/appium/python-client/pull/427
Needed to run python isort

Add events property

---

.travis.yml
tox.ini

For https://github.com/appium/python-client/issues/428

Run unittest with python3.8 on travis

---

README.md

Link is here.
https://pepy.tech/project/Appium-Python-Client

Add downloads badge to README

---

ci-jobs/functional/ios_setup.yml
ci-jobs/functional/run_ios_test.yml
ci-jobs/functional_test.yml

This fix comes from https://github.com/appium/ruby_lib_core/blob/master/ci-jobs/functional_test.yml.

Fix CI (Failed iOS)

---

appium/webdriver/extensions/android/common.py
appium/webdriver/extensions/applications.py
appium/webdriver/extensions/keyboard.py
appium/webdriver/webdriver.py
appium/webdriver/webelement.py
test/unit/webdriver/device/common_test.py
test/unit/webdriver/webdriver_test.py

per @KazuCocoa updated comment in #325

move commands from webdriver as mixins class

---

appium/webdriver/webdriver.py
appium/webdriver/webelement.py

Needs more changes to move commands to webelement, but for now just some changes are reverted.

Revert some changes to fix broken codes

---

azure-pipelines.yml
test/functional/android/find_by_accessibility_id_tests.py
test/functional/android/helper/test_helper.py
test/functional/android/network_connection_tests.py
test/functional/android/webdriver_tests.py
test/functional/ios/webdriver_tests.py
test/functional/test_helper.py

To make sure they works against appium@beta.
Also expected to detect such like https://github.com/appium/python-client/pull/460 earlier.
(I referred ruby client's one.)

[CI] Run functional tests nightly

---

appium/webdriver/extensions/execute_mobile_command.py
appium/webdriver/extensions/session.py
appium/webdriver/webdriver.py
appium/webdriver/webelement.py

For https://github.com/appium/python-client/issues/325

Move session/execute_mobile commands to mixin class

---

test/unit/webdriver/ime_test.py
test/unit/webdriver/nativekey_test.py

For https://github.com/appium/python-client/issues/283

Add IME unittest

---

ci-jobs/functional/run_ios_test.yml
ci-jobs/functional/save_appium_log.yml
test/functional/android/helper/test_helper.py
test/functional/ios/helper/test_helper.py

[Notes]
* For both iOS and Android
* Stop taking screenshot

ci: Take screen record as evidence

---

.pre-commit-config.yaml

To avoid uploading codes with mypy error

Add mypy to pre-commit

---

test/functional/ios/webdriver_tests.py

test: Fix test_clear flaky functional test

---

.gitignore
test/unit/webdriver/webelement_test.py

test: Add unit test for set_value (setImmediateValue)

---

.gitchangelog.rc
CHANGELOG.rst
README.md

From current master =3
Once this will be merged, I'll rename current master -> python2 and this python3 branch -> master

chore: Update readme and gitchangelog section role (#524)

---

ci-jobs/functional/run_android_test.yml
ci-jobs/functional/run_appium.yml
ci-jobs/functional_test.yml
test/functional/android/appium_service_tests.py

Added appium_service functional test

test: Add appium_service functional test

---

appium/webdriver/appium_service.py

Related to https://github.com/appium/python-client/issues/534

chore: Add the workaround to avoid service freezes on Windows

---

ci-jobs/functional_test.yml
test/functional/ios/helper/desired_capabilities.py

To follow the latest version
ref
* https://github.com/appium/ruby_lib_core/blob/master/ci-jobs/functional_test.yml
* https://github.com/microsoft/azure-pipelines-image-generation/releases

ci: upgrade xcode and macos

---

appium/webdriver/extensions/screen_record.py

* https://github.com/appium/appium-android-driver/pull/637
* https://github.com/appium/appium-support/pull/185

feat: Added descriptions for newly added screenrecord opts

---

appium/webdriver/webdriver.py

https://github.com/appium/java-client/pull/1506#discussion_r698003140
Appium drivers/plugins allow to override existing commands, so this PR leaves a log (debug) when such a case occurs.

feat: do not raise an error in case method is already defined

---

Pipfile
ci-jobs/functional/run_appium.yml
tox.ini

Trying to fix https://github.com/appium/python-client/issues/652

ci: remove ==2021.5.29

---

appium/webdriver/extensions/action_helpers.py

fixes https://github.com/appium/python-client/issues/672

fix: default duration in `tap`

---

Pipfile
appium/webdriver/extensions/action_helpers.py
appium/webdriver/extensions/ime.py
appium/webdriver/extensions/location.py
appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
appium/webdriver/webelement.py
setup.py

Fixes https://github.com/appium/python-client/issues/688 https://github.com/appium/python-client/issues/698
https://github.com/appium/ruby_lib_core/blob/master/lib/appium_lib_core/common/command.rb should be a good reference.

feat: add non-w3c but still need commands

---

appium/webdriver/webdriver.py
appium/webdriver/webelement.py

Hi! I faced with an issue while using `appium.find_element` with locators, that I used for my selenium tests. Is it possible to uncomment [that block](https://github.com/appium/python-client/pull/724/files#diff-646299ef4dd5d3b0e5d58632c99871ba450a1481e017654f4e95b11a2847c945R340) and use him in `web view` context only ?

chore: Update comments to locator patches

---

appium/options/mac/mac2/base.py

For https://github.com/appium/python-client/pull/756 to fix the lint

fix: fix options in mac2

---

.github/workflows/unit-test.yml
azure-pipelines.yml

Moving unit tests to GH Actions.
I'll do Win one as another PR.

ci: run unit tests on actions

---

appium/webdriver/mobilecommand.py
appium/webdriver/webdriver.py
test/unit/webdriver/webelement_test.py

I'll eventually add this endpoint in the selenium project, but let me add this endpoint in the Appium client so far.
https://w3c.github.io/webdriver/#dfn-statusv

feat: add status tentatively

---

README.md

docs: Improve usage examples

---

.github/workflows/unit-test.yml

ci: add py11 for the unit test

---

README.md

Some typos and grammar fixes I came across.

docs: typos and grammar fixes in README.md

---

README.md

Closes https://github.com/appium/python-client/issues/911
- https://github.com/appium/python-client/pull/909

docs: update README.md for v3

---

appium/webdriver/extensions/action_helpers.py

fix: typo in ActionHelpers

---

README.md

@KazuCocoa The example was missing one more import :)

docs: update W3C actions example in readme

---

appium/webdriver/webdriver.py

Just to update the old docstring

docs: update docstring

---

README.md
appium/webdriver/webdriver.py
test/functional/android/search_context/find_by_image_tests.py

- fix a few typos
- fix test to not use outdated `find_elements_by_image`

fix: typo and update test

---

appium/webdriver/extensions/android/common.py
test/functional/android/search_context/find_by_accessibility_id_tests.py
test/functional/android/search_context/find_by_image_tests.py
test/functional/android/search_context/find_by_uiautomator_tests.py
test/unit/webdriver/log_test.py
test/unit/webdriver/search_context/android_test.py
test/unit/webdriver/webelement_test.py

chore: remove non-reference variables, import and fix test names to run them properly

---

README.md
test/unit/webdriver/flutter_integration/flutter_integration_driver_test.py

closes https://github.com/appium/python-client/issues/916 's comment

docs: add options matrix in readme

---

pyproject.toml
uv.lock

They were made by:
```
uv run semantic-release version --patch
uv run semantic-release publish --tag=<specific tag>
```

chore: revert version created by release script checking
